name: Build Windows Exe

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to trigger it manually

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make Gradle Executable
      run: chmod +x ./gradlew

    - name: Build the App (.msi installer)
      run: ./gradlew packageMsi

    - name: Upload the .exe/.msi file
      uses: actions/upload-artifact@v4
      with:
        name: Metrolist-Windows-Installer
        path: build/compose/binaries/main/msi/*.msi
